openapi: "3.0.3"
info:
  title: Chat App API
  version: "1.0"
servers:
  - url: http://localhost:3000
paths:
  /signup:
    post:
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: password123
      responses:
        "200":
          description: User signed up successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
        "400":
          description: Error during sign-up
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /signin:
    post:
      summary: Sign in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: password123
      responses:
        "200":
          description: User signed in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
        "400":
          description: Error during sign-in
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /signout:
    post:
      summary: Sign out a user
      responses:
        "200":
          description: User signed out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Error during sign-out
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /protected:
    get:
      summary: Access a protected route
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Protected route accessed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
        "401":
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /products:
    get:
      summary: Fetch products
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Products fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "400":
          description: Error fetching products
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
